/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KvmSideDrawer {
        "opened": boolean;
        "titlemenu": string;
    }
}
declare global {
    interface HTMLKvmSideDrawerElement extends Components.KvmSideDrawer, HTMLStencilElement {
    }
    var HTMLKvmSideDrawerElement: {
        prototype: HTMLKvmSideDrawerElement;
        new (): HTMLKvmSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "kvm-side-drawer": HTMLKvmSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface KvmSideDrawer {
        "opened"?: boolean;
        "titlemenu"?: string;
    }
    interface IntrinsicElements {
        "kvm-side-drawer": KvmSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kvm-side-drawer": LocalJSX.KvmSideDrawer & JSXBase.HTMLAttributes<HTMLKvmSideDrawerElement>;
        }
    }
}
